### ISSUE TITLE
Story: Email notification - review is done. 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#100]
## As a user, I want to be able to receive a notification by email once my file's transcription review is done with its link. 

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] send an email notification to the creator of the file once it's transcription review is done with its link. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
