### ISSUE TITLE
Story: Error message - transcription failed

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#101]
## As a user, I want to be able to receive an error message if my transcription failed with the detail of why it failed. 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [ ] error message
- [ ] reason of failiure. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
