### ISSUE TITLE
Story: URL links

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#102]
## As a user, I want to have different URL links  for each of my file transcriptions view. 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 

- [x] give URL links to each transcription views. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
