### ISSUE TITLE
Story: Google login - Login button and link to Google

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#104]
## As a user I want to be able to login using Google by clicking on a login button and have a login view. 
- **Number of story points:** 5
- **Priority:** Mid
- **Risk:** Low

### Tasks TO DO: 

- [x] Add login button
- [x] Add login view  

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Get Radio Canada sign off
