### ISSUE TITLE
Story: DB Design and SQL script

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#105]
## As a user, I want to have all the necessary information stored and brought back to me when necessary. 

- **Number of story points:** 5
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] Create the SQL script. 
- [x] Make all the necessary changes.
- [x] Design the E/R diagram. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write tests
- [ ] Get Radio Canada sign off
