### ISSUE TITLE
Story: Check for duplicate users in the DB

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#108]
## As a user, I don't want my account information duplicated in the userdb.

- **Number of story points:** 1
- **Priority:** High
- **Risk:** Low

### Tasks TO DO: 
_Just need to implement a checker to see if the email is already in the user table before adding it in_ 

- [x] Find the best way to embed a video. Maybe use this https://video-react.js.org/components/player/

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off

![image](https://user-images.githubusercontent.com/13418355/51953982-7e60ee80-240c-11e9-96d2-e83a90d5ca1e.png)
