### ISSUE TITLE
Story: Edit transcription in File View 

### ISSUE THREAD

**Issue by williamkingbede** [FrankSauve/SearchAV#125]
## As a user, I want to be able to edit the transcription of a file in the file-transcription view.

- **Number of story points:** 3
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

- [x] Add 'Edit' and 'Save' buttons
- [x] Create new version of transcription and add it to the DB
- [x] Make that new version active and deactivate old version  
- [x] Persist changes

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write tests
- [ ] Get Radio Canada sign off
