### ISSUE TITLE
Story: Ask reviewer to review a file

### ISSUE THREAD

**Issue by williamkingbede** [FrankSauve/SearchAV#128]
## As a user, I want to be able to ask a reviewer, who is another user registered in the system, to review a file.

- **Number of story points:** 8
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

- [x] Add 'Demander une revision' button in FileView
- [x] Show list of users to select 
- [x] Add field 'ReviewerId' to file model and DB 
- [x] Add filter 'fichiers a reviser' 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write tests
- [x] Get Radio Canada sign off
