### ISSUE TITLE
Story: Upload long videos/audio

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#129]
## As a user, I want to be able to upload a video or file with a duration of at least 10 minutes.

- **Number of story points:** 3
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] Wait for RC to create a Google Cloud Storage Bucket
- [x] Install Google.Cloud.Storage.V1
- [x] [Add upload ](https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-csharp)
- [x] [Add Download](https://cloud.google.com/storage/docs/downloading-objects)

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write tests
- [ ] Get Radio Canada sign off
