### ISSUE TITLE
Story: Review file

### ISSUE THREAD

**Issue by williamkingbede** [FrankSauve/SearchAV#132]
## As a reviewer, I want to be able to review a file.

- **Number of story points:** 3
- **Priority:** High
- **Risk:** Low

### Tasks TO DO: 
If the user editing the file is the reviewer, upon saving the modifications, the flag "Révisé"  will be added to the file that is being under review.

- [x] Get user id.
- [x] Modify save transcription function to include logic checking if user is reviewer.
- [x] Add flag "Révisé" if user is the reviewer of the file.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write tests
- [ ] Get Radio Canada sign off
