### ISSUE TITLE
Story: Error message - Network error

### ISSUE THREAD

**Issue by PhilippeKuret** [FrankSauve/SearchAV#135]
As a user, I want to be able to receive an error message if there is a network error when doing a network call.

* **Number of story points:** 8
* **Priority:** Medium
* **Risk:** Low

### Tasks TO DO:
* [ ]  error message
* [ ]  reason of failiure.

### TO DO before closing the issue:
* [x]  Assign story to a feature (label)
* [x]  Assign an Iteration (milestone)
* [ ]  Link all commits, arch diagrams, summaries of discussions, etc
* [ ]  Have an explaination of the feature (demo)
* [ ]  Write tests
* [ ]  Get Radio Canada sign off
