### ISSUE TITLE
Add pagination for files in dashboard

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#156]
As a user, I want files to load quickly when I am in the dashboard.

* **Number of story points:** 5
* **Priority:** Medium
* **Risk:** Low

### Tasks TO DO:
* [x]  Add pagination to Grid and List View

### TO DO before closing the issue:
* [x]  Assign story to a feature (label)
* [x]  Assign an Iteration (milestone)
* [x]  Link all commits, arch diagrams, summaries of discussions, etc
* [x]  Have an explaination of the feature (demo)
* [ ]  Write tests
* [ ]  Get Radio Canada sign off
