### ISSUE TITLE
Story: Be able to edit the transcription on upload

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#16]
## As a user, I want to be able to edit the content of a transcription 
- **Number of story points:** 8
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

- [x] add an edit button 
- [x] add a save button
- [x] be able to edit the transcription 
- [x] be able to save the changes 
- [x] persist the changes 

### Steps:
1. Go to the 'Transcrire video' page
2. Choose an audio/video file
3. Click 'Go'
4. Click 'Edit'
5. Edit transcription
6. Click 'Save' 
Or
1. Go to the 'Videos' page
2. Click 'Edit' for one of the videos on the page
3. Edit transcription
4. Click 'Save'

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [ ] Get Radio Canada sign off
