### ISSUE TITLE
Story: File thumbnail and details box

### ISSUE THREAD

**Issue by PhilippeKuret** [FrankSauve/SearchAV#160]
## As a user, I want to be able to see who imported the file and when it was modified

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 

- [x] Display the thumbnail
- [x] Display the user who uploaded the video
- [x] Display last modified date

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explanation of the feature (demo)
- [x] Get Radio Canada sign off
