### ISSUE TITLE
Risky Story: Add word to transcription - Extension

### ISSUE THREAD

**Issue by PhilippeKuret** [FrankSauve/SearchAV#163]
## As a user, I want to be able to add a word

- **Number of story points:** 13
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] Add isAccurate in Word table
- [x] Add order in Word table
- [x] Add ordering logic for words when saving the transcript (SaveWords)
- [x] Improve add word logic for better timestamp estimation (HandleAdded)
- [x] Allow users to modify timestamps

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Get Radio Canada's approval
