### ISSUE TITLE
Risky Story: Delete words in transcription

### ISSUE THREAD

**Issue by PhilippeKuret** [FrankSauve/SearchAV#164]
## As a user, I want to be able to delete words in Transcription

- **Number of story points:** 13
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] Find a way to delete words in the transcription

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Get Radio Canada's approval
