### ISSUE TITLE
Risky Story: Modify words in transcription

### ISSUE THREAD

**Issue by PhilippeKuret** [FrankSauve/SearchAV#165]
## As a user, I want to be able to modify a word in transcription

- **Number of story points:** 13
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] Find a way to modify words in the transcription

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Get Radio Canada's approval
