### ISSUE TITLE
Story: Email notification - Review asked 

### ISSUE THREAD

**Issue by williamkingbede** [FrankSauve/SearchAV#169]
## As a reviewer, I want to be able to receive a notification by email once another user asked me to review a file. 

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Send an email notification to the reviewer of the file once review for the file is asked with its link. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Get Radio Canada sign off
