### ISSUE TITLE
Story: Add upload button and relate it to the transcription API

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#17]
## As a user, I want to be able to upload my file and have it transcribe. 
- **Number of story points:** 8
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

- [x] add an upload button
- [x] when the video is uploaded, transcribe it
- [x] show the transcription

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
