### ISSUE TITLE
Story: As a user, I want to add description of new file during upload

### ISSUE THREAD

**Issue by PhilippeKuret** [FrankSauve/SearchAV#177]
- Number of story points: 5
- Priority: Medium
- Risk: Low

**Tasks TO DO:**

- [x] Prompt user for a description **WHILE** video is being uploaded
- [x] Save the description

**TO DO before closing the issue:**

- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explanation of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
