### ISSUE TITLE
Story: As a user, I want to export a Google document

### ISSUE THREAD

**Issue by PhilippeKuret** [FrankSauve/SearchAV#179]
## As a user, I want to be able to download the Transcription in Google doc

- **Number of story points:** 10
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

- [x] Get document and create a google doc in drive

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
