### ISSUE TITLE
Risky Story: Create and connect the DB

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#18]
## As a user, I want to be able to have all the necessary information save in a Database and I want to be able to access them.  
- **Number of story points:** 20
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] decide on a Database design -- **needs to be efficient, save videos or audio files**
- [x] find the fastest DB structure. 
- [x] Create DB
- [x] Connect DB

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
