### ISSUE TITLE
Story: As a user, I want to export an .SRT file

### ISSUE THREAD

**Issue by PhilippeKuret** [FrankSauve/SearchAV#180]
## As a user, I want to be able to download the Transcription in .SRT

- **Number of story points:** 10
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] Learn how an .srt file is filled up
- [x] get the transcription by paragraph and find the timestamp of each paragraph
- [x] Create an srt file and write inside the timestamp and transcription based on how an srt file should be written

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
