### ISSUE TITLE
Story: History of changes - Store Title of changes

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#185]
## As a user, I want to be able to have a history/logs of changes that were done to the transcription. 

- **Number of story points:** 2
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 

- [x] HistoryTitle will be saved as ''CRÉATION DU FICHIER'' for the 1st version. Therefore, we need to add the HistoryTitle when we first save the transcription.
- [x] HistoryTitle will be saved as ''FICHIER RÉVISÉ'' when the Review is done.
- [x] HistoryTitle will be saved as ''MODIFICATIONS'' when a modification has been done in the text.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
