### ISSUE TITLE
Story: CI

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#2]
## As a developer, I want to have a continuous integration set up, so that I have all my pull requests tested.

- **Number of story points:** 5
- **Priority:** High
- **Risk:**  Medium

### Tasks TO DO: 

- [x] Pick a CI tool
- [x] Test Travis
- [x] Setup Appveyor - _Changed Travis for Appveyor, it is now working better and Appveyor can use a windows machine which makes working with it easier_

### TO DO before closing the issue: 
- Assign story to a feature (label) -- **Not applicable**
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- Write unit tests -- **Not applicable**
- Write demo steps -- **Not applicable**
