### ISSUE TITLE
Risky Story: Find a software/tool to convert video to audio under 10 megabytes

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#20]
## As a user, I want to be able to upload videos from 45s to 10mins and be able to have a transcription for it. 
- **Number of story points:** 20
- **Priority:** High
- **Risk:** High

**In order to be able to use Google Cloud for the transcription, we need to be able to have a tool that will convert the videos to audio file under 10 megabytes (requirement for Google Cloud)**

### Tasks TO DO: 

- [x] do some research on the converters available
- [x] test some of them and find the best solution 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Write tests
- [ ] Get Radio Canada sign off
