### ISSUE TITLE
Story: Video keyboard shortcuts

### ISSUE THREAD

**Issue by LeCleric** [FrankSauve/SearchAV#203]
## As a user, I would like to use keyboard shortcuts to navigate a video quickly. 

- **Number of story points:** 3
- **Priority:** Low
- **Risk:** Low

### Tasks TO DO: 

- [x] Implement a shortcut for a short-length seek going forwards or backwards a few seconds.
- [x] Implement a shortcut for pausing and playing.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explanation of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
