### ISSUE TITLE
Story: Grammar corrections (Antidote)

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#21]
## As a user, I want to be able to have suggestions to correct the transcription (grammar tool to correct the following: ponctuation, diffamation, etc.). 

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 

- [ ] Find a way to implement Antidote. 

Once the user clicks on "Edit": 
- [ ] Find a way to show the suggestions to the user. 
- [ ] Save those corrections. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [ ] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
