### ISSUE TITLE
Story: Add names to the transcription 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#22]
## As a user, I want to be able to add the names of the people talking. 

- **Number of story points:** 13
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

- [ ] maybe find a way so that the Speech-to-text detects new voice intonations (Beta product of Google Cloud - up to 4 voices). 
- [ ] add boxes in which we can add the name of the person talking 
- [ ] Save the changes

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
