### ISSUE TITLE
Story: Add tags/keywords to the transcriptions

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#23]
## As a user, I want to be able to add "tags" to categorize my file, so that it is easier to find it on the platform.  

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 

- [ ] add tags: have a autofill box (if the tag already exist, it takes it; if not, we create the new tag)
- [ ] have a search view on the platform where the tags are also filters. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
