### ISSUE TITLE
Story: Homepage

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#24]
## As a user, I want to be have a home page in which all the features are grouped nicely. 

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:** Medium
- _**Estimation of the ideal time**_: 10 hours

### Tasks TO DO: 

- [ ] all the files of the platform are shown (the most recent ones)
- [ ] upload button will be situated
- [ ] search bar with filters will be available to search into all the files of the platform

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write unit tests
- [ ] Write UI tests
- [ ] Write demo steps 
- [ ] Get TA signoff
