### ISSUE TITLE
Risky Story: Subtitles in the video

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#25]
## As a user, I want to be able to download the video file with the subtitles embedded in the video. 

- **Number of story points:** 20
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 
- [ ] merge the srt file and the video together 
- [ ] export a MP4 video with subtitles

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [ ] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
