### ISSUE TITLE
491: Drag and Drop multiple files

### ISSUE THREAD

**Issue by Sarb-F** [FrankSauve/SearchAV#292]
**491 info:**
* Why was this story/feature not going to be done?
* This issue was never brought up by our stakeholder. I figured it would be a nice to have for a user who has multiple files to upload. Rather than waiting for one file to complete before loading another, all of them can be uploaded simultaneously.

**Story info:**
As a user, I want to be able to upload multiple files for transcription.

**Tasks TO DO:**

**TO DO before closing the issue:**

- [x] Assign story to a feature (label)

- [x] Assign an Iteration (milestone)

- [x] Link all commits, arch diagrams, summaries of discussions, etc

- [x] Have an explanation of the feature (demo)
