### ISSUE TITLE
Organization of the project 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#3]
### Tasks TO DO: 

- [x] Find time sloth for which everybody can meet or be available for video conference.
**Tuesdays from 2:30pm to 3:30pm** 
- [x] Meet with Radio Canada to talk more about the project.
- [x] Set all the communication tools: GoogleDrive, GitHub and Slack. 

### TO DO before closing the issue: 
- Assign story to a feature (label) -- **Not applicable**
- [x] Assign an Iteration (milestone)
- Write unit tests -- **Not applicable**
- Write demo steps -- **Not applicable**
- Get TA signoff -- **Not applicable**
