### ISSUE TITLE
Story: Login using Google

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#35]
## As a user, I want to be able login using my Google account.

- **Number of story points:** 8
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

- [x] Implement the google api for login
- [x] Login button in the navbar
- [x] Store user in DB
- [x] Use jwt to authenticate routes

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
