### ISSUE TITLE
Story: Flags on videos

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#36]
## As a user, I want to be able to flag to show the status of the transcription.

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Low

### Flags (For now)
Automatisé --> Edité --> Révisé

### Tasks TO DO: 
- [x] Add visual flag to a file.
- [x] Store flag in DB

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
