### ISSUE TITLE
Story: Creator's Dashboard

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#37]
## As a creator, I want to be able to see all my uploaded files as well as all the files on my dashboard.

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:** High

### Tasks TO DO: 
The user of type ''Creator'' must be able to consult all of his/her files in a dashboard. -- This user should be able to see all his/her uploaded files and If it is a video, he/she should be able to see a Thumbnail of the video. 

- [x] Display all files in the system.
- [x] Fetch files from server.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
