### ISSUE TITLE
Story: History of changes - Name and date 

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#38]
## As a user, I want to be able to have a history/logs of changes that were done to the transcription. 

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 

- [x] Store history in the DB. 
- [x] Show history for each files on the "View File" page. 
~~- [ ] Find a way to show the history (Edits on the text).~~
- [x] Show name of the user and the modification date. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Get Radio Canada sign off
