### ISSUE TITLE
Story: Filters

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#39]
## As a creator, I want to be able to filter by flag and by "my files" on my dashboard.

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

Flags: Automatise, Edite, Revise.
- [x] Implement filters as links in form of cards (Mock ups).
- [x] Make files update accordingly once the filter is clicked.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [ ] Get Radio Canada sign off
