### ISSUE TITLE
Milestone 1 - Document

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#4]
Complete the following sections of the Google Doc: 
https://docs.google.com/document/d/1zc1eZw2G_NlCczSyjkrWYffKW11W1ENr4Hy9W0dNQBw/edit?usp=sharing

- [x] Team members
- [x] Project summary @AyoubeAkaouch 
- [x] Risk @AyoubeAkaouch 
- [x] Legal and Ethical issues @LeCleric 
- [x] Velocity @Raph1105
- [x] Overall Arch and Class diagram @FrankSauve 
- [x] Infrastructure
- [x] Name Conventions
- [x] Code
- [x] Testing and Continuous Integration
