### ISSUE TITLE
Story: Add a video player

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#40]
## As a user, I want to be able to play the file and see its transcription in one page.

- **Number of story points:** 8
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 
_When the user wants to see a specific transcription from his/her home page, he will click on it and will be redirected to the ''File view'' in which he/she can click on ''Edit'' and then be redirected to the ''Edit'' view. He/she can also play the file (have a video and a audio player), he/she can search in the transcription (have all the functionalities of the search in this view)._ 

- [x] Find the best way to embed a video. Maybe use this https://video-react.js.org/components/player/

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
