### ISSUE TITLE
Story: As a user, I want be able to save my transcription locally

### ISSUE THREAD

**Issue by anania-y** [FrankSauve/SearchAV#41]
### As a user, I want to be able to save the transcription locally in a text file.

- **Number of story points**: 3
- **Priority**: High
- **Risk**: Medium

### Tasks TO DO:

- [x] Create Save Button
- [x] Save a transcription locally using the save button
- [x] Get the file back into a jason string

### TO DO before closing the issue:

- [x]   Assign story to a feature (label)
- [x]   Assign an Iteration (milestone)
- [x]   Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Write tests
- [ ] Get Radio Canada sign off
