### ISSUE TITLE
Risky Story: Need to choose an API for the speech-to-text

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#5]
## As a user, I want to be able to have a minimum of 68% accuracy on transcriptions showed to me. 
- **Number of story points:** 40
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] Choose the speech-to-text API that we will use (needs to be in French and give timestamped transcriptions). 
- [x] @Raph1105 and @Sarb-F are testing Google Cloud -- _task #8_ **Current best option ~73% accuracy**
- [x] ~~@LeCleric and @FrankSauve are testing Amazon AWS -- _task #9_~~ **Needs the files to be store in Amazon cloud, and we need to whitelisted to use it in French**
- [x] ~~@PhilippeKuret  and @williamkingbede are testing Microsoft Azure -- _task #10_~~ **No timestamp**
- [x] ~~@anania-y  and @AyoubeAkaouch tested Nuance -- _task #11_~~ **Expensive and not the best option**
- [x] ~~@anania-y and @AyoubeAkaouch are testing Trint -- _task #12_~~**Only European-French**
- [x] ~~Test oTranscribe -- _task #13_~~ **Not a speech to text api**
- [x] ~~Test Temi -- _task #14_~~  **No french**

All the teams that are testing the speech-to-text API will fill the document: [Tests - API speech-to-text](https://docs.google.com/spreadsheets/d/1ieyH5XAhAMd4OXMVMRHhOihL241TNcaG7QtpAlWuC1o/edit?usp=sharing)

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Get Radio Canada's approval
