### ISSUE TITLE
Story: User role 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#54]
## As a user, I want to be able specify my role within the company.

- **Number of story points:** 5
- **Priority:** High
- **Risk:** Low

### Tasks TO DO: 

When the user logs in for the first time, we need to ask him what is his role within Radio Canada. The different possibilities are: Journalist, Edimaster, Social media expert, Editorial leader and Reviewer.  Journalist, Edimaster, Social media expert will be save as ''Creator'' and Editorial leader, Reviewer will be saved as ''Corrector''. They will have different rights and views on the platform. 

- [ ] Save the role of the user in a user table. 
- [ ] Create the page in which the user will identify his/her role. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [ ] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
