### ISSUE TITLE
Story: Highlight searched word in transcription

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#55]
## As a user, I want searched words to be highlighted in the transcription.

- **Number of story points:** 8
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

When we search for words, if there is only one occurrence of it, the cursor is directly positioned at the time in which the word is mentioned. 

- [x] Highlight words in the textarea using css
- [x] Highlight searched words in the textarea
- [x] Make the video seek to the first instance of the words

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explanation of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
