### ISSUE TITLE
Story: Delete file and transcription

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#56]
## As a user, I want to be able to delete one of my uploads (file and transcription). 

- **Number of story points:** 5
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] The user must be able to erase his files and transcription. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
