### ISSUE TITLE
Risky Story: Export Transcription 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#57]
## As a user, I want to be able to download the Transcription in any format. For now: .SRT, .DOC and Google doc. 

- **Number of story points:** 10
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [x] Create modal
- [x] Create the export button
- [x] Create the drop down options of format 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
