### ISSUE TITLE
Story: Corrector's Dashboard

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#59]
## As a corrector, I want to be able to see all files with the flag ""To be reviewed" on my dashboard.

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** High

### Tasks TO DO: 

- [ ] Fetch files from server.
- [ ] (Optional) Display a thumbnail of the video.
- [ ] Have the filter: "To be reviewed"

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [ ] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
