### ISSUE TITLE
Story: Search in the transcription

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#6]
## As a user, I want to be able to search in the transcription of an uploaded audio or video file.

- **Number of story points:** 13
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO:  
- [x] Obtain the time stamp of the searched word 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
