### ISSUE TITLE
Story: Review done, notify the creator

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#60]
## As a reviewer, I want to be able to notify a journalist that his transcription is revised. 

 **Number of story points:** 3
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO:  

- [x] Send email to the creator

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
