### ISSUE TITLE
Story: Email notifications - basic 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#61]
## As a user, I want to be able to receive my notifications by email. 

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Find a way to send a notification via email (Google account)

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Get Radio Canada sign off
