### ISSUE TITLE
Search in the platform - overall 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#62]
## As a user, I want to be able to search all the content uploaded to the tool.

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Search in all the transcriptions contents. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
