### ISSUE TITLE
Story: Creator's Dashboard Extension

### ISSUE THREAD

**Issue by williamkingbede** [FrankSauve/SearchAV#69]
## As a creator, I want to be able to see all my uploaded files as well as all the files on my dashboard.

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 
The user of type ''Creator'' must be able to consult all of his/her files in a dashboard. -- This user should be able to see all his/her uploaded files and and be able to see specific information for each file such as name of the user who uploaded the file, the duration, flag etc. 

- [x] Add a generic image for audio files.
- [x] Merge "mes videos" page and transcription page. (Dashboard)
- [x] Refactor file card to display necessary information for the user.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Get Radio Canada sign off
