### ISSUE TITLE
Risky Story: We have to be able to get timestamps for the transcribed text from the videos.

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#7]
## As a user, I want to be able to have a search that will tell me when the quote is said in the video. 

- **Number of story points:** 15
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 

- [ ] After choosing the speech-to-text API that we will use, we need to check how the time-stamping is done. 
- [ ] See how we can store it and index it. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
