### ISSUE TITLE
Story: Highlight words in transcription to seek at time in video/audio

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#73]
## As a user, I want to be able to highlight words to seek at the time where the word was said in the video/audio file.

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 
- ~~Use video-react library to seek at right time~~ 
- [x] Switch to using react-player
- [x] Use the react-player library to seek at right time

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explanation of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
