### ISSUE TITLE
Story: Add words to transcription

### ISSUE THREAD

**Issue by LeCleric** [FrankSauve/SearchAV#74]
## As a user, I would like to add words to a transcription.

- **Number of story points:** 11
- **Priority:** High
- **Risk:** High

### Tasks TO DO: 
Any user who chooses to edit a transcription should be able to add words tot he transcription without having to worry about the timestamps the words are tied to behind the scenes.

- [x] Develop method of generating timestamps for new words at the beginning of a transcription
- [x] Develop method of generating timestamps for new words at the middle of a transcription
- [x] Develop method of generating timestamps for new words at the end of a transcription

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explanation of the feature (demo)
- [x] Write tests
- [x] Get Radio Canada sign off
