### ISSUE TITLE
491: Highlight current sentence being said in a video/audio.

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#75]
# 491 info: 

- Why was this story/feature not going to be done?
It has been a nice-to-have feature for our project for a long while, having been mislabeled as necessary due to confusion with other [highlight related stories](https://github.com/FrankSauve/SearchAV/labels/highlighting). Since it's a feature which isn't necessary, but would require a fair deal of work to complete (multiple components interacting with one another, new ways of calling the DB, etc) it seems ideal for 491.

# Story info:
## As a creator, I want the current sentence that is being said in a video/audio to be highlighted in the transcription.

- **Number of story points:** 5
- **Priority:** Low
- **Risk:** High

### Tasks TO DO: 

- [x] Include a toggle for the feature (Activate using Alt+B, Deactivate using Alt+N)
- [x] Highlight the current sentence (line) or word that is being said in light grey
- [x] Make the highlight move down as the video plays

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explanation of the feature (demo)
- [x] Write tests
- [x] ~~Get Radio Canada sign off~~
