### ISSUE TITLE
Story: Add timestamps at the beginning and end of selected words in transcription

### ISSUE THREAD

**Issue by williamkingbede** [FrankSauve/SearchAV#76]
## As a user, I want to be able to see the timestamps at the beginning and end of the words that I have highlighted with the cursor in the transcription. 

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** High

### Tasks TO DO: 

- [x] Identify the first and last word. 
- [x] Get the corresponding timestamps for these words in the DB. 
- [x] Display the timestamps in the view at the beginning and end of the highlighted part. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
