### ISSUE TITLE
Story: Search in the Transcription - Extension

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#77]
## As a user, I want to be have a better search in the transcription. 

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 

- [x] adapt the search to the new DB structure.
- [x] return the word and the timestamp. 
- [ ] make it fault resistant. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explanation of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
