### ISSUE TITLE
Story: Persistent data (Setup DB)

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#78]
## As a user, I want my data to be saved.

- **Number of story points:** 5
- **Priority:** High
- **Risk:** Low

### Tasks TO DO: 

- [x] Select DBMS
- [x] Set up an ORM (Entity framework)

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [x] Write tests
- [ ] Get Radio Canada sign off
