### ISSUE TITLE
Story: Video-Transcription View

### ISSUE THREAD

**Issue by LeCleric** [FrankSauve/SearchAV#80]
## As a user, I want to be able to see a page with a chosen video, and its transcription.

- **Number of story points:** 5
- **Priority:** High
- **Risk:** Low

### Tasks TO DO: 
Add together the transcription and video functionalities from other stories into a single page for the user to access.

- [x] Display Video using VideoView.
- [x] Display the transcription tied to the chosen video.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explanation of the feature (demo)
- [x] Write tests
- [ ] Get Radio Canada sign off
