### ISSUE TITLE
Story: Profile picture and name in top right

### ISSUE THREAD

**Issue by FrankSauve** [FrankSauve/SearchAV#81]
## As a user, I want to be see my picture and my name in the top right of the navbar.

- **Number of story points:** 1
- **Priority:** Mid
- **Risk:** Low

### Tasks TO DO: 

- [x] Get the name and picture from google (Look at the login method in Login.tsx component)
- [x] Display name and picture in navbar

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Get Radio Canada sign off
