### ISSUE TITLE
Story: Creator's Dashboard style customization

### ISSUE THREAD

**Issue by LeCleric** [FrankSauve/SearchAV#82]
## As a creator, I would like to be able to edit the appearance of the creator's dashboard.

- **Number of story points:** 2
- **Priority:** Low
- **Risk:** Low

### Tasks TO DO: 
Allow for the user to resize parts of the page and recolour the site

- [ ] Resize page elements
- [ ] Recolour the navbar, background and foreground elements

### TO DO before closing the issue: 
- [ ] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explanation of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
