### ISSUE TITLE
Story: Edit automated transcription in dashboard 

### ISSUE THREAD

**Issue by williamkingbede** [FrankSauve/SearchAV#84]
## As a user, I want to be able to edit the automated transcription of the file I have just uploaded in my dashboard.

- **Number of story points:** 5
- **Priority:** High
- **Risk:** Medium

### Tasks TO DO: 

- [x] Find a way to get the id of the file 
- [x] Create new version of transcription and add it to the DB
- [x] Make that new version active and deactivate old version  
- [x] Persist changes

### Steps:
1. Go to the 'Transcrire video' page
2. Choose an audio/video file
3. Click 'Go'
4. Click 'Edit'
5. Edit transcription
6. Click 'Save' 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Have an explanation of the feature (demo)
- [x] Write tests
- [ ] Get Radio Canada sign off
