### ISSUE TITLE
Story: Duplicate files 

### ISSUE THREAD

**Issue by williamkingbede** [FrankSauve/SearchAV#85]
## As a user, I want to avoid uploading the same file twice.

- **Number of story points:** 3
- **Priority:** Medium
- **Risk:** Medium

### Tasks TO DO: 

- [x] Verify in DB if the file already exist during transcription (we will refer to the title for now).
- [x] Notify the user who's uploading the file that a file with the same title already exists on the platform.  
- [x] Notify the user who's modifying a title, that the title name already exists.

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [ ] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explanation of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
