### ISSUE TITLE
Story: Google login - Data Safety

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#87]
## As a user, I want to my data to be safe when I log in. 
- **Number of story points:** 8
- **Priority:** Mid
- **Risk:** Low

### Tasks TO DO: 

- [x] Make sure that the user's data is safe. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Get Radio Canada sign off
