### ISSUE TITLE
Story: Google login - Data Storage

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#88]
## As a user, I want my name and email to be stored, so the system reconized me. 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Store email in DB
- [x] Store name in DB

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
