### ISSUE TITLE
Story: File description

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#89]
## As a user, I want to be able to give a description to my file. 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Add the column ''Description'' to the File table. 
- [x] Add the field to write a description. 
- [x] Save the description. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Get Radio Canada's approval
