### ISSUE TITLE
Story: Change file's name

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#90]
## As a user, I want to be able to change the file's name. 

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Add dropdown option to "Modifier titre" 
- [x] Show the field to change the file's name. 
- [x] Save the new name in DB. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Unit test
- [ ] Get Radio Canada's approval
