### ISSUE TITLE
Story: Search in the platform - title 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#91]
## As a user, I want to be able to search in all the uploaded file, by title. 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Search by title

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [x] Get Radio Canada's approval
