### ISSUE TITLE
Story: Search in the platform - description 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#92]
## As a user, I want to be able to search in all the uploaded file, by description. 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Search by description

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Get Radio Canada's approval
