### ISSUE TITLE
Story: Change view - Grid, List. 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#93]
## As a user, I want to be able to change my dashboard's view. 

- **Number of story points:** 8
- **Priority:** Low
- **Risk:** Low

### Tasks TO DO: 

- [x] Search by title

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Get Radio Canada's approval
