### ISSUE TITLE
Story: Automatic thumbnail 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#94]
## As a user, I want to be able have an automatic thumbnail for my file, if there is none I want Radio Canada's logo to be shown. 

- **Number of story points:** 8
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] Automatic thumbnail for video
- [ ] Radio Canada's logo for audio files

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Get Radio Canada's approval
