### ISSUE TITLE
Story: Skip lines in the transcription (organization) 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#95]
## As a user, I want to be able to skip line in the transcription in order to have an organized view by paragraphs. 

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:** High

### Tasks TO DO: 

- [x] Be able to skip lines
- [x] Save the changes in the transcription so that the view stays the same. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Get Radio Canada's approval
