### ISSUE TITLE
Story: Show timestamp at the beginning of each paragraph in the transcription 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#96]
## As a user, I want to be able to search in all the uploaded file, by title. 

- **Number of story points:** 13
- **Priority:** Medium
- **Risk:** High

### Tasks TO DO: 

**In order to be able to do this story completly we need to finish #95**
- [ ] show timestamp at the beginning of each paragraph 
- [ ] have a column to the left of the transcription with the timestamps

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Get Radio Canada's approval
