### ISSUE TITLE
491: History of changes - versions, transcriptions shown 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#97]
# 491 info: 

- Why was this story/feature not going to be done?

Radio Canada mentioned that it would be nice to be able to see each version of the history of changes. 
This story is a nice-to-have feature for our project and is related to the must-have features stories: [History of changes - Store Title of changes](https://github.com/FrankSauve/SearchAV/issues/185) and [History of changes - Name and date](https://github.com/FrankSauve/SearchAV/issues/38). Both of the must-have stories were done by myself (Raphaëlle Giraud). 
Since it's a feature which was not necessary and required to make multiple components interacting with one another, new calls to the DB, creating new classes and modals it seemed like an ideal feature for 491.  

# Link to the demo: 

https://youtu.be/PYZXT6hjZNQ

# Link to the pull request 

You can find the [pull request here](https://github.com/FrankSauve/SearchAV/pull/291). This pull request shows all the commits and the difference between what has been done previously (how the history of changes was shown) and how it is now presented/handled in order to be able to revert to a previous version. 

# Story info:
## As a user, I want to be able to see the old versions of the transcription according to the history. 

- **Number of story points:** 5
- **Priority:** Low
- **Risk:** Medium

### Tasks TO DO: 

- [x] Be able to see previous versions of the transcription 
- [x] Be able to 'revert' to a previous version 
- [x] When a file has been reverted, show this in the History of changes

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [x] Link all commits, arch diagrams, summaries of discussions, etc
