### ISSUE TITLE
Story: Email notification - transcription is done - Extension 

### ISSUE THREAD

**Issue by ghost** [FrankSauve/SearchAV#99]
## As a user, I want to be able to receive a notification by email once my file's transcription is done with its link. 

- **Number of story points:** 5
- **Priority:** Medium
- **Risk:** Low

### Tasks TO DO: 

- [x] send an email notification to the creator of the file once it's transcription is done **with the link of the transcription view of the file**. 

### TO DO before closing the issue: 
- [x] Assign story to a feature (label)
- [x] Assign an Iteration (milestone)
- [ ] Link all commits, arch diagrams, summaries of discussions, etc
- [ ] Have an explaination of the feature (demo)
- [ ] Write tests
- [ ] Get Radio Canada sign off
